cleanup and corrected the ports

diff --git a/electrumx/bin/init b/electrumx/bin/init
--- a/electrumx/bin/init
+++ b/electrumx/bin/init
@@ -4,4 +4,33 @@ if [ ! -e "${SSL_CERTFILE}" ] || [ ! -e "${SSL_KEYFILE}" ]; then
   openssl req -newkey rsa:2048 -sha256 -nodes -x509 -days 365 -subj "/O=ElectrumX" -keyout "${SSL_KEYFILE}" -out "${SSL_CERTFILE}"
 fi
 
-exec /usr/local/bin/rpcd & /usr/local/bin/electrumx_server
+#exec /usr/local/bin/rpcd & /usr/local/bin/electrumx_server
+
+# Start the first process
+electrumx_server &
+status=$?
+if [ $status -ne 0 ]; then
+  echo "Failed to start electrumx_server: $status"
+  exit $status
+fi
+
+# Start the second process
+rpcd &
+status=$?
+if [ $status -ne 0 ]; then
+  echo "Failed to start rpcd: $status"
+  exit $status
+fi
+
+# Check whether the process is running every 60 seconds
+while sleep 60; do
+  ps aux | grep rpcd | grep -v grep
+  PROCESS_1_STATUS=$?
+  ps aux | grep electrumx_server | grep -v grep
+  PROCESS_2_STATUS=$?
+  
+  if [ $PROCESS_1_STATUS -ne 0 -o $PROCESS_2_STATUS -ne 0 ]; then
+    echo "One of the processes has already exited."
+    exit 1
+  fi
+done
